# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: CivicActions Vanilla Jekyll Site
email: your-email@civicactions.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/ca-jekyll-vanilla" # the subpath of your site, e.g. /blog. Also update pa11y testing package.json.
url: "https://civicactions.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: CivicActions
github_username:  civicactions

github_info:
  organization: civicactions
  repository: ca-jekyll-vanilla
  default_branch: main

# Build settings
remote_theme: 18f/uswds-jekyll
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from

kramdown:
  smart_quotes: ["apos", "apos", "quot", "quot"]

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - pa11y_output.txt
  - .sass-cache
  - .jekyll-cache
  - gemfiles
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - package.json
  - package-lock.json
  - lint
  - cypress
  - cypress.json
  - .gitignore
  - .github
